# .github/workflows/gradle-build-pr.yml
name: Test PRs
on: pull_request
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: test
